/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.CuentasxCobrarLetras;

import Entidades.Cabeces;
import Entidades.CabecesId;
import Entidades.Clientes;
import Entidades.Otros.NroLetras;
import Entidades.Sistema;
import Entidades.Tipocambio;
import Entidades.Usuarios;
import Mantenimiento.Navegacion;
import Presentacion.MENU001;
import Servicios.Servicio_Cliente;
import Servicios.Servicio_TipoCambio;
import Servicios.facturacion.Servicio_Documentos;
import com.toedter.calendar.JDateChooser;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Black Jack
 */
public class IU_GenerarLetraRenovada extends javax.swing.JFrame {

    /**
     * Creates new form GenerarLetraRenovada
     */
    private DefaultTableModel modelTabla;
    private int filaSeleccionada;
    private MENU001 menu001;
    private Usuarios usuarios;
    private JTable tablaLetras;
    private String rol;
    private FREP043 frep43;
    
    private Navegacion navegacion;
    private JTextField[] componentes;
    private ArrayList<Integer> numMaximo;
    private ArrayList<String> tipoDato;
    
    ArrayList<NroLetras> letras_detalle;
    Sistema sisLet;
    Servicio_Documentos serv_doc;
    Tipocambio t;
    protected Servicio_Cliente sc;
    
    public IU_GenerarLetraRenovada(DefaultTableModel modelTabla, int filaSeleccionada, MENU001 menu001, Usuarios usuarios, JTable tablaLetras, String rol, FREP043 frep43) {
        initComponents();
        setLocationRelativeTo(null);
        
        sc = new Servicio_Cliente(null);
        serv_doc = new Servicio_Documentos();   
        
        this.modelTabla = modelTabla;
        this.filaSeleccionada = filaSeleccionada;
        this.frep43 = frep43;
        this.tablaLetras = tablaLetras;
        
        dt_fechaVencimiento.setMinSelectableDate(new Date());
        
        cargarDatos();
        
        crearArrayComponente();
        crearArrayNumMax();
        crearArrayTipoDato();
        navegacion = new Navegacion(componentes, numMaximo, tipoDato, btnGenerarRenovacion);
        asignarEvento();
    }
    
    private void crearArrayComponente() {
        componentes = new JTextField[2];
        componentes[0] = txtAdelanto;
        componentes[1] = txtGastosAdministrativos;

    }
    
    private void crearArrayNumMax() {
        numMaximo = new ArrayList();
        numMaximo.add(1000000);
        numMaximo.add(1000000);
    }

    private void crearArrayTipoDato() {
        tipoDato = new ArrayList();
        tipoDato.add("D");
        tipoDato.add("D");
    }
    
    private void asignarEvento() {
        for (int i = 0; i < componentes.length; i++) {
            componentes[i].addKeyListener(navegacion);
        }
    }

    
    private void cargarDatos() {
        txtNumeroLetra.setText(String.valueOf(modelTabla.getValueAt(filaSeleccionada, 1)));
        txtNumeroLetra2.setText(String.valueOf(modelTabla.getValueAt(filaSeleccionada, 1)));
        txtFechaEmision.setText(String.valueOf(modelTabla.getValueAt(filaSeleccionada, 4)));
        txtFacturaReferencia.setText(String.valueOf(modelTabla.getValueAt(filaSeleccionada, 12)));
        txtMontoLetra.setText(String.valueOf(modelTabla.getValueAt(filaSeleccionada, 7)));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFacturaReferencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMontoLetra = new javax.swing.JTextField();
        txtAdelanto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMontoARenovar = new javax.swing.JTextField();
        btnGenerarRenovacion = new javax.swing.JButton();
        btnSalirRenovacion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtGastosAdministrativos = new javax.swing.JTextField();
        dt_fechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroLetra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroLetra2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtRenovacion = new javax.swing.JTextField();
        cbTipoLetra = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fecha de Emisión: ");

        txtFechaEmision.setEditable(false);

        jLabel2.setText("Factura de Referencia: ");

        txtFacturaReferencia.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("GENERACION LETRA RENOVADA/REFINANCIADA");

        jLabel4.setText("Monto de Letra: ");

        jLabel5.setText("Adelanto:");

        txtMontoLetra.setEditable(false);

        txtAdelanto.setText("0");
        txtAdelanto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdelantoFocusLost(evt);
            }
        });
        txtAdelanto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdelantoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdelantoKeyTyped(evt);
            }
        });

        jLabel7.setText("Monto a Renovar : ");

        jLabel9.setText("Fecha de Vencimiento: ");

        txtMontoARenovar.setEditable(false);

        btnGenerarRenovacion.setText("Generar");
        btnGenerarRenovacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRenovacionActionPerformed(evt);
            }
        });

        btnSalirRenovacion.setText("Salir");
        btnSalirRenovacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRenovacionActionPerformed(evt);
            }
        });

        jLabel10.setText("Gastos Administrativos:");

        txtGastosAdministrativos.setText("0");
        txtGastosAdministrativos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGastosAdministrativosFocusLost(evt);
            }
        });
        txtGastosAdministrativos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGastosAdministrativosKeyReleased(evt);
            }
        });

        dt_fechaVencimiento.setDateFormatString("yyyy-MM--dd");
        dt_fechaVencimiento.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("N° Letra: ");

        txtNumeroLetra.setEditable(false);
        txtNumeroLetra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setText("N° de  Letra: ");

        txtNumeroLetra2.setEditable(false);

        jLabel11.setText("Nro.de Operación:");

        cbTipoLetra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RN - Renovación", "RF - Refinanciación" }));

        jLabel12.setText("Tipo de Letra:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGenerarRenovacion)
                        .addGap(201, 201, 201)
                        .addComponent(btnSalirRenovacion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAdelanto)
                                .addComponent(txtGastosAdministrativos)
                                .addComponent(txtMontoLetra)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(38, 38, 38)
                            .addComponent(txtMontoARenovar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(dt_fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFacturaReferencia)
                                .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNumeroLetra2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRenovacion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNumeroLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFacturaReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMontoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdelanto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtGastosAdministrativos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMontoARenovar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dt_fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtRenovacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtNumeroLetra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarRenovacion)
                    .addComponent(btnSalirRenovacion))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarRenovacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRenovacionActionPerformed
        //validar
        serv_doc = new Servicio_Documentos();
        int numeroRenovacion;
        if(txtMontoARenovar.getText().equals("")||dt_fechaVencimiento.getDate() == null|| txtRenovacion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Error: Verificar Fecha de vencimiento, Monto a Renovar o Nro. Renovación", "Datos imcompletos", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                numeroRenovacion = Integer.parseInt(txtRenovacion.getText());

            sisLet = serv_doc.getSis("Número de Letra");
            int opcion = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Generar la Letra Renovada ?", "Confirmacion", JOptionPane.YES_NO_OPTION);
            Date dateFechaEmision = null;
            if (opcion == JOptionPane.YES_OPTION) {
                String fechaEmision = txtFechaEmision.getText();
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            try {
                dateFechaEmision = formatter.parse(fechaEmision);
            } catch (ParseException ex) {
                System.out.println("Error en formato de fecha "+ex.getMessage());
            }
                
            int diferenciaDias = (int) ((dateFechaEmision.getTime()-dt_fechaVencimiento.getDate().getTime())/86400000);            
                System.out.println("Diferencia de Dias : "+ diferenciaDias);
                NroLetras nroLetra = new NroLetras();
                nroLetra.setNro(1);
                nroLetra.setDiasVcto(diferenciaDias);//temporal calcularlo
                nroLetra.setImporte(Double.parseDouble(txtMontoARenovar.getText()));
                nroLetra.setFechaVec(dt_fechaVencimiento.getDate());
                nroLetra.setNroRenovacion(numeroRenovacion);
                String tipoLetra = String.valueOf(cbTipoLetra.getSelectedItem()).substring(0, 2);
                System.out.println("tipoLetra:" + tipoLetra);
               
             
            ArrayList<Cabeces> cabec_letras = SetCabeces(nroLetra, tipoLetra);
            if(serv_doc.GuardarLetras_Varias(cabec_letras)){
                JOptionPane.showMessageDialog(null, "Guardado con Exito", "Guardar", JOptionPane.INFORMATION_MESSAGE);
                serv_doc.actualizarSis(sisLet);
                frep43.limpiar();
                frep43.model.getDataVector().removeAllElements();
                frep43.model.fireTableDataChanged();
                frep43.iniciarTabla(tablaLetras);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Error al Guardar", "Guardar", JOptionPane.ERROR_MESSAGE);
            }

        }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Nro. Renovación debe ser un numero entero", "Numero", JOptionPane.ERROR_MESSAGE);
        }
     }

        
    }//GEN-LAST:event_btnGenerarRenovacionActionPerformed

    private ArrayList<Cabeces> SetCabeces(NroLetras letra, String tipoLetra){
        ArrayList<Cabeces> lista = new ArrayList<>();
        String numero = txtNumeroLetra.getText();//sisLet.getUltimonumero()+1;
        String numeroRenovacion = numero+"-" + tipoLetra + letra.getNroRenovacion();
        System.out.println("NUMERO CABECES y RENOVACIÓN: "+numeroRenovacion);
        int serie = sisLet.getSerie();
        int i=0;
        t = serv_doc.getTipoCambio(new Date()); //Fecha de hoy
        try{
            System.out.println(t);
        }catch(Exception e){
            t = new Tipocambio();
            t.setFecha(new Date());
            new Servicio_TipoCambio().Insertar(t);
        }
        
        Clientes c;
        c = sc.getxNombre(String.valueOf(modelTabla.getValueAt(filaSeleccionada, 0)));
        System.out.println("Nombre obtenido "+ modelTabla.getValueAt(filaSeleccionada, 0));
        System.out.println("Cliente a guardar "+ c.getNombre());
            Cabeces cab = new Cabeces();
            cab.setTipoperacion("3");
            cab.setClientes(c);
            cab.setTipocambio(t);
            cab.setTipocambio_1(t.getValorventa());
            cab.setId(new CabecesId("V", "06",String.valueOf(serie),String.valueOf(numeroRenovacion)));
            cab.setTotal(letra.getImporte());
            cab.setMoneda("2");//Dolares
            JDateChooser chooser = dt_fechaVencimiento;
            cab.setFechavencimiento(chooser.getDate());
            cab.setLetraFacbol("");//sin documentos de referencia
            
            lista.add(cab);

        //sisLet.setUltimonumero(numero);
        return lista;
    }
        
    private void txtAdelantoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdelantoKeyReleased
        actualizaMontoARenovar();
    }//GEN-LAST:event_txtAdelantoKeyReleased

    private void txtAdelantoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdelantoKeyTyped
        
    }//GEN-LAST:event_txtAdelantoKeyTyped

    private void txtAdelantoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdelantoFocusLost
        // TODO add your handling code here:
        if(txtAdelanto.getText().trim().equals("")){
            txtAdelanto.setText("0");
        }
    }//GEN-LAST:event_txtAdelantoFocusLost

    private void txtGastosAdministrativosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGastosAdministrativosFocusLost
        if(txtGastosAdministrativos.getText().trim().equals("")){
            txtGastosAdministrativos.setText("0");
        }
    }//GEN-LAST:event_txtGastosAdministrativosFocusLost

    private void btnSalirRenovacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRenovacionActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirRenovacionActionPerformed

    private void txtGastosAdministrativosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGastosAdministrativosKeyReleased
        actualizaMontoARenovar();
    }//GEN-LAST:event_txtGastosAdministrativosKeyReleased

    public void actualizaMontoARenovar(){
        Double adelanto;
        Double gastosAdministrativos;
        
        if(!txtAdelanto.getText().trim().equals("")&&!txtGastosAdministrativos.getText().trim().equals("")){
           try {
            adelanto = Double.parseDouble(txtAdelanto.getText());
            gastosAdministrativos = Double.parseDouble(txtGastosAdministrativos.getText());
            DecimalFormat formato = new DecimalFormat("#.00");
            txtMontoARenovar.setText(formato.format(Double.parseDouble(txtMontoLetra.getText())- adelanto + gastosAdministrativos).replace(",", "."));
            
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese Numeros válidos", "Error Número Ingresado", JOptionPane.WARNING_MESSAGE);
            }
        
        }
            
    
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(IU_GenerarLetraRenovada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(IU_GenerarLetraRenovada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(IU_GenerarLetraRenovada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(IU_GenerarLetraRenovada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
 //       java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IU_GenerarLetraRenovada().setVisible(true);
//            }
//       });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarRenovacion;
    private javax.swing.JButton btnSalirRenovacion;
    private javax.swing.JComboBox cbTipoLetra;
    public com.toedter.calendar.JDateChooser dt_fechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAdelanto;
    private javax.swing.JTextField txtFacturaReferencia;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtGastosAdministrativos;
    private javax.swing.JTextField txtMontoARenovar;
    private javax.swing.JTextField txtMontoLetra;
    private javax.swing.JTextField txtNumeroLetra;
    private javax.swing.JTextField txtNumeroLetra2;
    private javax.swing.JTextField txtRenovacion;
    // End of variables declaration//GEN-END:variables

}
