package Entidades;
// Generated 14/03/2016 06:02:40 AM by Hibernate Tools 3.6.0



/**
 * AccesosId generated by hbm2java
 */
public class AccesosId  implements java.io.Serializable {


     private Integer idrol;
     private Integer idprograma;

    public AccesosId() {
    }

    public AccesosId(Integer idrol, Integer idprograma) {
       this.idrol = idrol;
       this.idprograma = idprograma;
    }
   
    public Integer getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(Integer idrol) {
        this.idrol = idrol;
    }
    public Integer getIdprograma() {
        return this.idprograma;
    }
    
    public void setIdprograma(Integer idprograma) {
        this.idprograma = idprograma;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AccesosId) ) return false;
		 AccesosId castOther = ( AccesosId ) other; 
         
		 return ( (this.getIdrol()==castOther.getIdrol()) || ( this.getIdrol()!=null && castOther.getIdrol()!=null && this.getIdrol().equals(castOther.getIdrol()) ) )
 && ( (this.getIdprograma()==castOther.getIdprograma()) || ( this.getIdprograma()!=null && castOther.getIdprograma()!=null && this.getIdprograma().equals(castOther.getIdprograma()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdrol() == null ? 0 : this.getIdrol().hashCode() );
         result = 37 * result + ( getIdprograma() == null ? 0 : this.getIdprograma().hashCode() );
         return result;
   }   


}


