package Entidades;

/**
 * CabecesId generated by hbm2java
 */
public class CabecesId  implements java.io.Serializable {

     private String tipotra;
     private String tipodoc;
     private String nrorserie;
     private String nrodocumento;

    public CabecesId() {
        
    }
    
    public CabecesId(String tipodoc, String nrodocumento) {
        this.tipodoc = tipodoc;
        this.nrodocumento = nrodocumento;
    }
    
    public CabecesId(String tipotra,String tipodoc, String nrodocumento) {
        this.tipotra = tipotra;
        this.tipodoc = tipodoc;
        this.nrodocumento = nrodocumento;
    }
    
    public CabecesId(String tipotra, String tipodoc, String nrorserie, String nrodocumento) {
       this.tipotra = tipotra;
       this.tipodoc = tipodoc;
       this.nrorserie = nrorserie;
       this.nrodocumento = nrodocumento;
    }
   
    public String getTipotra() {
        return this.tipotra;
    }
    
    public void setTipotra(String tipotra) {
        this.tipotra = tipotra;
    }
    public String getTipodoc() {
        return this.tipodoc;
    }
    
    public void setTipodoc(String tipodoc) {
        this.tipodoc = tipodoc;
    }
    public String getNrorserie() {
        return this.nrorserie;
    }
    
    public void setNrorserie(String nrorserie) {
        this.nrorserie = nrorserie;
    }
    public String getNrodocumento() {
        return this.nrodocumento;
    }
    
    public void setNrodocumento(String nrodocumento) {
        this.nrodocumento = nrodocumento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CabecesId) ) return false;
		 CabecesId castOther = ( CabecesId ) other; 
         
		 return ( (this.getTipotra()==castOther.getTipotra()) || ( this.getTipotra()!=null && castOther.getTipotra()!=null && this.getTipotra().equals(castOther.getTipotra()) ) )
 && ( (this.getTipodoc()==castOther.getTipodoc()) || ( this.getTipodoc()!=null && castOther.getTipodoc()!=null && this.getTipodoc().equals(castOther.getTipodoc()) ) )
 && ( (this.getNrorserie()==castOther.getNrorserie()) || ( this.getNrorserie()!=null && castOther.getNrorserie()!=null && this.getNrorserie().equals(castOther.getNrorserie()) ) )
 && ( (this.getNrodocumento()==castOther.getNrodocumento()) || ( this.getNrodocumento()!=null && castOther.getNrodocumento()!=null && this.getNrodocumento().equals(castOther.getNrodocumento()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTipotra() == null ? 0 : this.getTipotra().hashCode() );
         result = 37 * result + ( getTipodoc() == null ? 0 : this.getTipodoc().hashCode() );
         result = 37 * result + ( getNrorserie() == null ? 0 : this.getNrorserie().hashCode() );
         result = 37 * result + ( getNrodocumento() == null ? 0 : this.getNrodocumento().hashCode() );
         return result;
   }   


}


