package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cabeces generated by hbm2java
 */
public class Cabeces  implements java.io.Serializable {

   
     private CabecesId id;
     private Sucursales sucursales;
     private Bancos bancos;
     private Tipocambio tipocambio;
     private Ubigeo ubigeo;
     private Vendedores vendedores;
     private Usuarios usuarios;
     private Cabecproformas cabecproformas;
     private Transportistas transportistas;
     private Clientes clientes;
     private PuntosVenta puntosventa;
     private String ordencompra;


     
     private String marca;
     private String observaciones;
     private String modelo;
     private String ordenTransportista;
     
     private String letraPlanilla;
     private Date fechaLetPla;
     
     private int txtgen;

    public Date getFechaLetPla() {
        return fechaLetPla;
    }

    public void setFechaLetPla(Date fechaLetPla) {
        this.fechaLetPla = fechaLetPla;
    }

    public String getLetraPlanilla() {
        return letraPlanilla;
    }

    public void setLetraPlanilla(String letraPlanilla) {
        this.letraPlanilla = letraPlanilla;
    }
     private String siniestro;
     private Integer nrorenovacion;
     private String tipoperacion;
     private Double importebruto;
     private Double valorventa;
     private Double igv;
     private Double total;
     private String moneda;
     private String comision;
     private Double porcentaje;
     private Date fechavencimiento;
     private Integer nroguia;
     
     private Date fechaemigr;
     
     private Double costototal;
     private String ncFacbol;
     private Double ncFacbolImporte;
     private String puntollegada;
     private String letraFacbol;
     private String tipoletra;
     private String letraNrobanco;
     private String letraBanco;
     private String letraTipo;
     private Integer almacen;
     private Double tipocambio_1;
     private String estado;
     
     private int genDocElect;
     private Date fechaEnvio;
     
     private Set cabecproformases = new HashSet(0);
     private Set detalleeses = new HashSet(0);
     private Set cabecsalvars = new HashSet(0);
     private Set detallenotas = new HashSet(0);
     private Set pagoses = new HashSet(0);
     private Set renovacionLetras = new HashSet(0);

    public Cabeces() {
    }

    public Cabeces(CabecesId id, int genDocElect) {
        this.id = id;
        this.genDocElect = genDocElect;
    }
	
    public Cabeces(CabecesId id) {
        this.id = id;
    }
    public Cabeces(CabecesId id, Sucursales sucursales, Bancos bancos, Tipocambio tipocambio, Ubigeo ubigeo, Vendedores vendedores, Usuarios usuarios, 
            Cabecproformas cabecproformas, Transportistas transportistas, Clientes clientes, 
            String marca,  String placa, String modelo, String ordenTransportista,
            String siniestro, Integer nrorenovacion, String tipoperacion, Double importebruto, Double valorventa, Double igv, Double total, String moneda, String comision, Double porcentaje, Date fechavencimiento, Integer nroguia, Double costototal, String ncFacbol, Double ncFacbolImporte, String puntollegada, String letraFacbol, String tipoletra, String letraNrobanco, String letraBanco, String letraTipo, Integer almacen, Double tipocambio_1, String estado, 
            int genDocElect, Date fechaEnvio,
            Set cabecproformases, Set detalleeses, Set cabecsalvars, Set detallenotas, Set pagoses, Set renovacionLetras) {
       this.id = id;
       this.sucursales = sucursales;
       this.bancos = bancos;
       this.tipocambio = tipocambio;
       this.ubigeo = ubigeo;
       this.vendedores = vendedores;
       this.usuarios = usuarios;
       this.transportistas = transportistas;
       this.clientes = clientes;
       this.cabecproformas = cabecproformas;
       
       this.marca = marca;
       this.observaciones = placa;
       this.modelo = modelo;
       this.ordenTransportista = ordenTransportista;
       
       this.siniestro = siniestro;
       this.nrorenovacion = nrorenovacion;
       this.tipoperacion = tipoperacion;
       this.importebruto = importebruto;
       this.valorventa = valorventa;
       this.igv = igv;
       this.total = total;
       this.moneda = moneda;
       this.comision = comision;
       this.porcentaje = porcentaje;
       this.fechavencimiento = fechavencimiento;
       this.nroguia = nroguia;
       this.costototal = costototal;
       this.ncFacbol = ncFacbol;
       this.ncFacbolImporte = ncFacbolImporte;
       this.puntollegada = puntollegada;
       this.letraFacbol = letraFacbol;
       this.tipoletra = tipoletra;
       this.letraNrobanco = letraNrobanco;
       this.letraBanco = letraBanco;
       this.letraTipo = letraTipo;
       this.almacen = almacen;
       this.tipocambio_1 = tipocambio_1;
       this.estado = estado;
       this.cabecproformases = cabecproformases;
       this.detalleeses = detalleeses;
       this.cabecsalvars = cabecsalvars;
       this.detallenotas = detallenotas;
       this.pagoses = pagoses;
       this.renovacionLetras = renovacionLetras;
       
       this.genDocElect = genDocElect;
       this.fechaEnvio = fechaEnvio;
    }
   
    public CabecesId getId() {
        return this.id;
    }
    
    public void setId(CabecesId id) {
        this.id = id;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public Bancos getBancos() {
        return this.bancos;
    }
    
    public void setBancos(Bancos bancos) {
        this.bancos = bancos;
    }
    public Tipocambio getTipocambio() {
        return this.tipocambio;
    }
    
    public void setTipocambio(Tipocambio tipocambio) {
        this.tipocambio = tipocambio;
    }
    
    public Ubigeo getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(Ubigeo ubigeo) {
        this.ubigeo = ubigeo;
    }
    
    public Vendedores getVendedores() {
        return this.vendedores;
    }
    
    public void setVendedores(Vendedores vendedores) {
        this.vendedores = vendedores;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Transportistas getTransportistas() {
        return this.transportistas;
    }
    
    public void setTransportistas(Transportistas transportistas) {
        this.transportistas = transportistas;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    
    public PuntosVenta getPuntosventa() {
        return puntosventa;
    }

    public void setPuntosventa(PuntosVenta puntosventa) {
        this.puntosventa = puntosventa;
    }

    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getObservaciones() {
        return observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getOrdenTransportista() {
        return ordenTransportista;
    }

    public void setOrdenTransportista(String ordenTransportista) {
        this.ordenTransportista = ordenTransportista;
    }

    public String getSiniestro() {
        return siniestro;
    }

    public void setSiniestro(String siniestro) {
        this.siniestro = siniestro;
    }
    
    public Integer getNrorenovacion() {
        return this.nrorenovacion;
    }
    
    public void setNrorenovacion(Integer nrorenovacion) {
        this.nrorenovacion = nrorenovacion;
    }
    public String getTipoperacion() {
        return this.tipoperacion;
    }
    
    public void setTipoperacion(String tipoperacion) {
        this.tipoperacion = tipoperacion;
    }
    public Double getImportebruto() {
        return this.importebruto;
    }
    
    public void setImportebruto(Double importebruto) {
        this.importebruto = importebruto;
    }
    public Double getValorventa() {
        return this.valorventa;
    }
    
    public void setValorventa(Double valorventa) {
        this.valorventa = valorventa;
    }
    public Double getIgv() {
        return this.igv;
    }
    
    public void setIgv(Double igv) {
        this.igv = igv;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public String getComision() {
        return this.comision;
    }
    
    public void setComision(String comision) {
        this.comision = comision;
    }
    public Double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }
    public Integer getNroguia() {
        return this.nroguia;
    }
    
    public void setNroguia(Integer nroguia) {
        this.nroguia = nroguia;
    }

    public Date getFechaemigr() {
        return fechaemigr;
    }

    public void setFechaemigr(Date fechaemigr) {
        this.fechaemigr = fechaemigr;
    }
    
    public Double getCostototal() {
        return this.costototal;
    }
    
    public void setCostototal(Double costototal) {
        this.costototal = costototal;
    }
    public String getNcFacbol() {
        return this.ncFacbol;
    }
    
    public void setNcFacbol(String ncFacbol) {
        this.ncFacbol = ncFacbol;
    }
    public Double getNcFacbolImporte() {
        return this.ncFacbolImporte;
    }
    
    public void setNcFacbolImporte(Double ncFacbolImporte) {
        this.ncFacbolImporte = ncFacbolImporte;
    }
    public String getPuntollegada() {
        return this.puntollegada;
    }
    
    public void setPuntollegada(String puntollegada) {
        this.puntollegada = puntollegada;
    }
    public String getLetraFacbol() {
        return this.letraFacbol;
    }
    
    public void setLetraFacbol(String letraFacbol) {
        this.letraFacbol = letraFacbol;
    }
    public String getTipoletra() {
        return this.tipoletra;
    }
    
    public void setTipoletra(String tipoletra) {
        this.tipoletra = tipoletra;
    }
    public String getLetraNrobanco() {
        return this.letraNrobanco;
    }
    
    public void setLetraNrobanco(String letraNrobanco) {
        this.letraNrobanco = letraNrobanco;
    }
    
    public String getLetraBanco() {
        return this.letraBanco;
    }
    
    public void setLetraBanco(String letraBanco) {
        this.letraBanco = letraBanco;
    }
    public String getLetraTipo() {
        return this.letraTipo;
    }
    
    public void setLetraTipo(String letraTipo) {
        this.letraTipo = letraTipo;
    }
    
    public Integer getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Integer almacen) {
        this.almacen = almacen;
    }
    public Double getTipocambio_1() {
        return this.tipocambio_1;
    }
    
    public void setTipocambio_1(Double tipocambio_1) {
        this.tipocambio_1 = tipocambio_1;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCabecproformases() {
        return this.cabecproformases;
    }
    
    public void setCabecproformases(Set cabecproformases) {
        this.cabecproformases = cabecproformases;
    }
    public Set getDetalleeses() {
        return this.detalleeses;
    }
    
    public void setDetalleeses(Set detalleeses) {
        this.detalleeses = detalleeses;
    }
    public Set getCabecsalvars() {
        return this.cabecsalvars;
    }
    
    public void setCabecsalvars(Set cabecsalvars) {
        this.cabecsalvars = cabecsalvars;
    }
    public Set getDetallenotas() {
        return this.detallenotas;
    }
    
    public void setDetallenotas(Set detallenotas) {
        this.detallenotas = detallenotas;
    }
    public Set getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }
    public Set getRenovacionLetras() {
        return this.renovacionLetras;
    }
    
    public void setRenovacionLetras(Set renovacionLetras) {
        this.renovacionLetras = renovacionLetras;
    }

    public Cabecproformas getCabecproformas() {
        return this.cabecproformas;
    }
    
    public void setCabecproformas(Cabecproformas cabecproformas) {
        this.cabecproformas = cabecproformas;
    }
    
    public int getGenDocElect() {
        return this.genDocElect;
    }
    
    public void setGenDocElect(int genDocElect) {
        this.genDocElect = genDocElect;
    }
    
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    
     /**
     * Get the value of txtgen
     *
     * @return the value of txtgen
     */
    public int getTxtgen() {
        return txtgen;
    }

    /**
     * Set the value of txtgen
     *
     * @param txtgen new value of txtgen
     */
    public void setTxtgen(int txtgen) {
        this.txtgen = txtgen;
    }
    
    public String getOrdencompra() {
        return ordencompra;
    }

    public void setOrdencompra(String ordencompra) {
        this.ordencompra = ordencompra;
    }

    @Override
    public String toString() {
        return "Cabeces{" 
                + "-" + id.getTipodoc()
                + "-" + id.getNrodocumento() 
                + "-" + id.getNrorserie()
                + ", genDocElect=" + genDocElect + ", fechaEnvio=" + fechaEnvio + '}';
    }

}