package Entidades;
// Generated 04/10/2013 04:32:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cabecsugerido generated by hbm2java
 */
public class Cabecsugerido  implements java.io.Serializable {


     private Integer idsugerido;
     private Importadores importadores;
     private String nrofacimportacion;
     private Date fechaingresostock;
     private String nroguia;
     private Date fechapedido;
     private Date fechaembarque;
     private String estado;
     private Double total;
     
     // Agregando (De Disan Trading a M&D
     private Double factorCosto;
     
     private Set<Tramites> tramiteses = new HashSet<Tramites>(0);
     private Set<Detallees> detalleeses = new HashSet<Detallees>(0);
     private Set<Detallesugerido> detallesugeridos = new HashSet<Detallesugerido>(0);

    public Cabecsugerido() {
    }

    public Cabecsugerido(Importadores importadores, String nrofacimportacion, Date fechaingresostock, String nroguia, Date fechapedido, Date fechaembarque, String estado, Double total, Set<Tramites> tramiteses, Set<Detallees> detalleeses, Set<Detallesugerido> detallesugeridos, Double factorCosto) {
       this.importadores = importadores;
       this.nrofacimportacion = nrofacimportacion;
       this.fechaingresostock = fechaingresostock;
       this.nroguia = nroguia;
       this.fechapedido = fechapedido;
       this.fechaembarque = fechaembarque;
       this.estado = estado;
       this.total = total;
       this.tramiteses = tramiteses;
       this.detalleeses = detalleeses;
       this.detallesugeridos = detallesugeridos;
       
       this.factorCosto = factorCosto;
    }
   
    public Integer getIdsugerido() {
        return this.idsugerido;
    }
    
    public void setIdsugerido(Integer idsugerido) {
        this.idsugerido = idsugerido;
    }
    public Importadores getImportadores() {
        return this.importadores;
    }
    
    public void setImportadores(Importadores importadores) {
        this.importadores = importadores;
    }
    public String getNrofacimportacion() {
        return this.nrofacimportacion;
    }
    
    public void setNrofacimportacion(String nrofacimportacion) {
        this.nrofacimportacion = nrofacimportacion;
    }
    public Date getFechaingresostock() {
        return this.fechaingresostock;
    }
    
    public void setFechaingresostock(Date fechaingresostock) {
        this.fechaingresostock = fechaingresostock;
    }
    public String getNroguia() {
        return this.nroguia;
    }
    
    public void setNroguia(String nroguia) {
        this.nroguia = nroguia;
    }
    public Date getFechapedido() {
        return this.fechapedido;
    }
    
    public void setFechapedido(Date fechapedido) {
        this.fechapedido = fechapedido;
    }
    public Date getFechaembarque() {
        return this.fechaembarque;
    }
    
    public void setFechaembarque(Date fechaembarque) {
        this.fechaembarque = fechaembarque;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Set<Tramites> getTramiteses() {
        return this.tramiteses;
    }
    
    public void setTramiteses(Set<Tramites> tramiteses) {
        this.tramiteses = tramiteses;
    }
    public Set<Detallees> getDetalleeses() {
        return this.detalleeses;
    }
    
    public void setDetalleeses(Set<Detallees> detalleeses) {
        this.detalleeses = detalleeses;
    }
    public Set<Detallesugerido> getDetallesugeridos() {
        return this.detallesugeridos;
    }
    
    public void setDetallesugeridos(Set<Detallesugerido> detallesugeridos) {
        this.detallesugeridos = detallesugeridos;
    }

    public Double getFactorCosto() {
        return this.factorCosto;
    }
    
    public void setFactorCosto(Double factorCosto) {
        this.factorCosto = factorCosto;
    }
}


