package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer idcliente;
     private Ubigeo ubigeo;
     private Transportistas transportistas;
     private String nombre;
     private String ruc;
     private String direccion;
     private String plaza;
     
     private String clase;
     
     private String telefonofijo;
     private String telefonofijo2;
     private String telefonocel;
     private String email;
     private String contacto;
     private String clave;
     private String estadoweb;
     private String causabloqueo;
     private Date fechabloqueo;
     private String verstock;
     private Double credito;
     private String observacion;
     private Double descuento1;
     private Double descuento2;
     private Double descuento3;
     private Double descuento4;
     private String tipo;
     private Set cabeceses = new HashSet(0);
     private Set sucursaleses = new HashSet(0);
     private Set cabecproformases = new HashSet(0);
     private Set cabecwebs = new HashSet(0);
     private Set cabecsalvars = new HashSet(0);
     private Set detalleeses = new HashSet(0);

    public Clientes() {
    }

    public Clientes(Ubigeo ubigeo, Transportistas transportistas, String nombre, String ruc, String direccion, String plaza, String clase, String telefonofijo, String telefonofijo2, String telefonocel, String email, String contacto, String clave, String estadoweb, String causabloqueo, Date fechabloqueo, String verstock, Double credito, String observacion, Double descuento1, Double descuento2, Double descuento3, Double descuento4, String tipo, Set cabeceses, Set sucursaleses, Set cabecproformases, Set cabecwebs, Set cabecsalvars, Set detalleeses) {
       this.ubigeo = ubigeo;
       this.transportistas = transportistas;
       this.nombre = nombre;
       this.ruc = ruc;
       this.direccion = direccion;
       this.plaza = plaza;
       
       this.clase = clase;
       
       this.telefonofijo = telefonofijo;
       this.telefonofijo2 = telefonofijo2;
       this.telefonocel = telefonocel;
       this.email = email;
       this.contacto = contacto;
       this.clave = clave;
       this.estadoweb = estadoweb;
       this.causabloqueo = causabloqueo;
       this.fechabloqueo = fechabloqueo;
       this.verstock = verstock;
       this.credito = credito;
       this.observacion = observacion;
       this.descuento1 = descuento1;
       this.descuento2 = descuento2;
       this.descuento3 = descuento3;
       this.descuento4 = descuento4;
       this.tipo = tipo;
       this.cabeceses = cabeceses;
       this.sucursaleses = sucursaleses;
       this.cabecproformases = cabecproformases;
       this.cabecwebs = cabecwebs;
       this.cabecsalvars = cabecsalvars;
       this.detalleeses = detalleeses;
    }
   
    public Integer getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }
    
    public Ubigeo getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(Ubigeo ubigeo) {
        this.ubigeo = ubigeo;
    }
    
    public Transportistas getTransportistas() {
        return this.transportistas;
    }
    
    public void setTransportistas(Transportistas transportistas) {
        this.transportistas = transportistas;
    }
    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    public String getPlaza() {
        return this.plaza;
    }
    
    public void setPlaza(String plaza) {
        this.plaza = plaza;
    }
    
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }
    
    public String getTelefonofijo() {
        return this.telefonofijo;
    }
    
    public void setTelefonofijo(String telefonofijo) {
        this.telefonofijo = telefonofijo;
    }
    
    public String getTelefonofijo2() {
        return this.telefonofijo2;
    }
    
    public void setTelefonofijo2(String telefonofijo2) {
        this.telefonofijo2 = telefonofijo2;
    }
    
    public String getTelefonocel() {
        return this.telefonocel;
    }
    
    public void setTelefonocel(String telefonocel) {
        this.telefonocel = telefonocel;
    }
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    public String getEstadoweb() {
        return this.estadoweb;
    }
    
    public void setEstadoweb(String estadoweb) {
        this.estadoweb = estadoweb;
    }
    
    public String getCausabloqueo() {
        return this.causabloqueo;
    }
    
    public void setCausabloqueo(String causabloqueo) {
        this.causabloqueo = causabloqueo;
    }
    
    public Date getFechabloqueo() {
        return this.fechabloqueo;
    }
    
    public void setFechabloqueo(Date fechabloqueo) {
        this.fechabloqueo = fechabloqueo;
    }
    
    public String getVerstock() {
        return this.verstock;
    }
    
    public void setVerstock(String verstock) {
        this.verstock = verstock;
    }
    
    public Double getCredito() {
        return this.credito;
    }
    
    public void setCredito(Double credito) {
        this.credito = credito;
    }
    
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    
    public Double getDescuento1() {
        return this.descuento1;
    }
    
    public void setDescuento1(Double descuento1) {
        this.descuento1 = descuento1;
    }
    
    public Double getDescuento2() {
        return this.descuento2;
    }
    
    public void setDescuento2(Double descuento2) {
        this.descuento2 = descuento2;
    }
    
    public Double getDescuento3() {
        return this.descuento3;
    }
    
    public void setDescuento3(Double descuento3) {
        this.descuento3 = descuento3;
    }
    
    public Double getDescuento4() {
        return this.descuento4;
    }
    
    public void setDescuento4(Double descuento4) {
        this.descuento4 = descuento4;
    }
    
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    public Set getCabeceses() {
        return this.cabeceses;
    }
    
    public void setCabeceses(Set cabeceses) {
        this.cabeceses = cabeceses;
    }
    
    public Set getSucursaleses() {
        return this.sucursaleses;
    }
    
    public void setSucursaleses(Set sucursaleses) {
        this.sucursaleses = sucursaleses;
    }
    
    public Set getCabecproformases() {
        return this.cabecproformases;
    }
    
    public void setCabecproformases(Set cabecproformases) {
        this.cabecproformases = cabecproformases;
    }
    
    public Set getCabecwebs() {
        return this.cabecwebs;
    }
    
    public void setCabecwebs(Set cabecwebs) {
        this.cabecwebs = cabecwebs;
    }
    
    public Set getCabecsalvars() {
        return this.cabecsalvars;
    }
    
    public void setCabecsalvars(Set cabecsalvars) {
        this.cabecsalvars = cabecsalvars;
    }
    
    public Set getDetalleeses() {
        return this.detalleeses;
    }
    
    public void setDetalleeses(Set detalleeses) {
        this.detalleeses = detalleeses;
    }
    
    public String toString(){
        return nombre;
    }
}