package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA

/**
 * Control generated by hbm2java
 */
public class Control  implements java.io.Serializable {

     private Integer idcontrol;
     private Ubigeo ubigeo;
     private Roles roles;
     private String ruc;
     private String nombrempresa;
     private String rutadb;
     private String rutaprogramas;
     private String rutareportes;
     private String rutaimagenes;
     private String nombrealmacen;
     private String nombrealmacen2;
     private Integer mesdemanda;
     private Integer mesproyeccion;
     private Integer impuestoigv;
     private Integer nrolineafac;
     private String vercontoperfact;
     
     private String opedef;
     
     private Integer nrolineagr;
     private Integer nrolineabol;
     private Integer nrolineanc;
     private Integer nrolineand;
     private Integer almacen;
     private String correo;
     private char stock0;
     private String telefonos;
     private int monedarepuestos;
     private String docfactdefecto;
     
     private String ubidpto;
     private String ubiprov;
     private String ubidist;
     
     private String rutalogoproforma;
     private String rutalogoingreso;

     private Integer color;
     
    public Control() {
    }
    
    public Control(char stock0) {
        this.stock0 = stock0;
    }
    
    public Control(String vercontoperfact, Ubigeo ubigeo, Roles roles, String ruc, String nombrempresa, String rutadb, String rutaprogramas, String rutareportes, 
                   String rutaimagenes, String nombrealmacen, String nombrealmacen2, Integer mesdemanda, Integer mesproyeccion, 
                   Integer impuestoigv, Integer nrolineafac, Integer nrolineagr, Integer nrolineabol, Integer nrolineanc, 
                   Integer nrolineand, Integer almacen, String correo, char stock0, String telefonos) {
       this.vercontoperfact = vercontoperfact;
       this.ubigeo = ubigeo;
       this.roles = roles;
       this.ruc = ruc;
       this.nombrempresa = nombrempresa;
       this.rutadb = rutadb;
       this.rutaprogramas = rutaprogramas;
       this.rutareportes = rutareportes;
       this.rutaimagenes = rutaimagenes;
       this.nombrealmacen = nombrealmacen;
       this.nombrealmacen2 = nombrealmacen2;
       this.mesdemanda = mesdemanda;
       this.mesproyeccion = mesproyeccion;
       this.impuestoigv = impuestoigv;
       this.nrolineafac = nrolineafac;
       this.nrolineagr = nrolineagr;
       this.nrolineabol = nrolineabol;
       this.nrolineanc = nrolineanc;
       this.nrolineand = nrolineand;
       this.almacen = almacen;
       this.correo = correo;
       this.stock0 = stock0;
       this.telefonos = telefonos;
    }
   
    public Integer getIdcontrol() {
        return this.idcontrol;
    }
    
    public void setIdcontrol(Integer idcontrol) {
        this.idcontrol = idcontrol;
    }
    
    public Ubigeo getUbigeo() {
        return this.ubigeo;
    }
    
    public void setUbigeo(Ubigeo ubigeo) {
        this.ubigeo = ubigeo;
    }
    
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    public String getRuc() {
        return ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    
    public String getNombrempresa() {
        return this.nombrempresa;
    }
    
    public void setNombrempresa(String nombrempresa) {
        this.nombrempresa = nombrempresa;
    }
    
    public String getRutadb() {
        return this.rutadb;
    }
    
    public void setRutadb(String rutadb) {
        this.rutadb = rutadb;
    }
    
    public String getRutaprogramas() {
        return this.rutaprogramas;
    }
    
    public void setRutaprogramas(String rutaprogramas) {
        this.rutaprogramas = rutaprogramas;
    }
    
    public String getRutareportes() {
        return this.rutareportes;
    }
    
    public void setRutareportes(String rutareportes) {
        this.rutareportes = rutareportes;
    }
    
    public String getRutaimagenes() {
        return this.rutaimagenes;
    }
    
    public void setRutaimagenes(String rutaimagenes) {
        this.rutaimagenes = rutaimagenes;
    }
    
    public String getNombrealmacen() {
        return this.nombrealmacen;
    }
    
    public void setNombrealmacen(String nombrealmacen) {
        this.nombrealmacen = nombrealmacen;
    }

    public String getNombrealmacen2() {
        return nombrealmacen2;
    }

    public void setNombrealmacen2(String nombrealmacen2) {
        this.nombrealmacen2 = nombrealmacen2;
    }
    
    public Integer getMesdemanda() {
        return this.mesdemanda;
    }
    
    public void setMesdemanda(Integer mesdemanda) {
        this.mesdemanda = mesdemanda;
    }
    
    public Integer getMesproyeccion() {
        return this.mesproyeccion;
    }
    
    public void setMesproyeccion(Integer mesproyeccion) {
        this.mesproyeccion = mesproyeccion;
    }
    
    public Integer getImpuestoigv() {
        return this.impuestoigv;
    }
    
    public void setImpuestoigv(Integer impuestoigv) {
        this.impuestoigv = impuestoigv;
    }
    
    public Integer getNrolineafac() {
        return this.nrolineafac;
    }
    
    public void setNrolineafac(Integer nrolineafac) {
        this.nrolineafac = nrolineafac;
    }

    public Integer getNrolineagr() {
        return nrolineagr;
    }

    public void setNrolineagr(Integer nrolineagr) {
        this.nrolineagr = nrolineagr;
    }
    
    public Integer getNrolineabol() {
        return this.nrolineabol;
    }
    
    public void setNrolineabol(Integer nrolineabol) {
        this.nrolineabol = nrolineabol;
    }
    
    public Integer getNrolineanc() {
        return this.nrolineanc;
    }
    
    public void setNrolineanc(Integer nrolineanc) {
        this.nrolineanc = nrolineanc;
    }
    
    public Integer getNrolineand() {
        return this.nrolineand;
    }
    
    public void setNrolineand(Integer nrolineand) {
        this.nrolineand = nrolineand;
    }
    
    public Integer getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Integer almacen) {
        this.almacen = almacen;
    }
    
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    
    public char getStock0() {
        return this.stock0;
    }
    
    public void setStock0(char stock0) {
        this.stock0 = stock0;
    }

    public String getTelefonos() {
        return telefonos;
    }

    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }

    public int getMonedarepuestos() {
        return monedarepuestos;
    }

    public void setMonedarepuestos(int monedarepuestos) {
        this.monedarepuestos = monedarepuestos;
    }

    public String getDocfactdefecto() {
        return docfactdefecto;
    }

    public void setDocfactdefecto(String docfactdefecto) {
        this.docfactdefecto = docfactdefecto;
    }

    public String getRutalogoproforma() {
        return rutalogoproforma;
    }

    public void setRutalogoproforma(String rutalogoproforma) {
        this.rutalogoproforma = rutalogoproforma;
    }

    public String getRutalogoingreso() {
        return rutalogoingreso;
    }

    public void setRutalogoingreso(String rutalogoingreso) {
        this.rutalogoingreso = rutalogoingreso;
    }

    public String getUbidpto() {
        return ubidpto;
    }

    public void setUbidpto(String ubidpto) {
        this.ubidpto = ubidpto;
    }

    public String getUbiprov() {
        return ubiprov;
    }

    public void setUbiprov(String ubiprov) {
        this.ubiprov = ubiprov;
    }

    public String getUbidist() {
        return ubidist;
    }

    public void setUbidist(String ubidist) {
        this.ubidist = ubidist;
    }
    
    public String getVercontoperfact() {
        return this.vercontoperfact;
    }
    
    public void setVercontoperfact(String vercontoperfact) {
        this.vercontoperfact = vercontoperfact;
    }

    public Integer getColor() {
        return color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    public String getOpedef() {
        return opedef;
    }

    public void setOpedef(String opedef) {
        this.opedef = opedef;
    }   
}