package Entidades;
// Generated 18/09/2013 12:58:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Detallees generated by hbm2java
 */
public class Detallees  implements java.io.Serializable {


     private Integer iddetalles;
     private Cabeces cabeces;
     
     private Integer nroguia;
     private Date fechaemigr;
     
     private Operaciones operaciones;
     private Repuestos repuestos;
     private Cabecsugerido cabecsugerido;
     private Clientes clientes;
     private Cabecsalvar cabecsalvar;
     private Integer cantpedida;
     private Integer cantentregada;
     private String codsecundario;
     private Integer nroalternativo;
     private Integer origenalmacen;
     private Integer destinoalmacen;
     private Double preciolista;
     private Double costopromedio;
     private Double ultimocosto;
     private Integer ordentrabajo;
     private String estadotransaccion;
     private Double descuento1;
     private Double descuento2;
     private Double descuento3;
     private Double descuento4;
     private Integer almacen;
     private String motivo;
     private Integer nroingreso;
     private Date fecha;
     
     private String disponibilidad;

    public Detallees() {
    }

    public Detallees(Cabeces cabeces, Operaciones operaciones, Repuestos repuestos, Cabecsugerido cabecsugerido, Clientes clientes, Cabecsalvar cabecsalvar, Integer cantpedida, Integer cantentregada, String codsecundario, Integer nroalternativo, Integer origenalmacen, Integer destinoalmacen, Double preciolista, Double costopromedio, Double ultimocosto, Integer ordentrabajo, String estadotransaccion, Double descuento1, Double descuento2, Double descuento3, Double descuento4, Integer almacen, String motivo, Integer nroingreso, Date fecha
                    ,String disponibilidad) {
       this.cabeces = cabeces;
       this.operaciones = operaciones;
       this.repuestos = repuestos;
       this.cabecsugerido = cabecsugerido;
       this.clientes = clientes;
       this.cabecsalvar = cabecsalvar;
       this.cantpedida = cantpedida;
       this.cantentregada = cantentregada;
       this.codsecundario = codsecundario;
       this.nroalternativo = nroalternativo;
       this.origenalmacen = origenalmacen;
       this.destinoalmacen = destinoalmacen;
       this.preciolista = preciolista;
       this.costopromedio = costopromedio;
       this.ultimocosto = ultimocosto;
       this.ordentrabajo = ordentrabajo;
       this.estadotransaccion = estadotransaccion;
       this.descuento1 = descuento1;
       this.descuento2 = descuento2;
       this.descuento3 = descuento3;
       this.descuento4 = descuento4;
       this.almacen = almacen;
       this.motivo = motivo;
       this.nroingreso = nroingreso;
       this.fecha = fecha;
       this.disponibilidad = disponibilidad;
    }
    
    public Integer getNroguia() {
        return this.nroguia;
    }
    
    public void setNroguia(Integer nroguia) {
        this.nroguia = nroguia;
    }
    
    public Date getFechaemigr() {
        return fechaemigr;
    }

    public void setFechaemigr(Date fechaemigr) {
        this.fechaemigr = fechaemigr;
    }
   
    public Integer getIddetalles() {
        return this.iddetalles;
    }
    
    public void setIddetalles(Integer iddetalles) {
        this.iddetalles = iddetalles;
    }
    public Cabeces getCabeces() {
        return this.cabeces;
    }
    
    public void setCabeces(Cabeces cabeces) {
        this.cabeces = cabeces;
    }
    public Operaciones getOperaciones() {
        return this.operaciones;
    }
    
    public void setOperaciones(Operaciones operaciones) {
        this.operaciones = operaciones;
    }
    public Repuestos getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Repuestos repuestos) {
        this.repuestos = repuestos;
    }
    public Cabecsugerido getCabecsugerido() {
        return this.cabecsugerido;
    }
    
    public void setCabecsugerido(Cabecsugerido cabecsugerido) {
        this.cabecsugerido = cabecsugerido;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Cabecsalvar getCabecsalvar() {
        return this.cabecsalvar;
    }
    
    public void setCabecsalvar(Cabecsalvar cabecsalvar) {
        this.cabecsalvar = cabecsalvar;
    }
    public Integer getCantpedida() {
        return this.cantpedida;
    }
    
    public void setCantpedida(Integer cantpedida) {
        this.cantpedida = cantpedida;
    }
    public Integer getCantentregada() {
        return this.cantentregada;
    }
    
    public void setCantentregada(Integer cantentregada) {
        this.cantentregada = cantentregada;
    }
    public String getCodsecundario() {
        return this.codsecundario;
    }
    
    public void setCodsecundario(String codsecundario) {
        this.codsecundario = codsecundario;
    }
    public Integer getNroalternativo() {
        return this.nroalternativo;
    }
    
    public void setNroalternativo(Integer nroalternativo) {
        this.nroalternativo = nroalternativo;
    }
    public Integer getOrigenalmacen() {
        return this.origenalmacen;
    }
    
    public void setOrigenalmacen(Integer origenalmacen) {
        this.origenalmacen = origenalmacen;
    }
    public Integer getDestinoalmacen() {
        return this.destinoalmacen;
    }
    
    public void setDestinoalmacen(Integer destinoalmacen) {
        this.destinoalmacen = destinoalmacen;
    }
    public Double getPreciolista() {
        return this.preciolista;
    }
    
    public void setPreciolista(Double preciolista) {
        this.preciolista = preciolista;
    }
    public Double getCostopromedio() {
        return this.costopromedio;
    }
    
    public void setCostopromedio(Double costopromedio) {
        this.costopromedio = costopromedio;
    }
    public Double getUltimocosto() {
        return this.ultimocosto;
    }
    
    public void setUltimocosto(Double ultimocosto) {
        this.ultimocosto = ultimocosto;
    }
    public Integer getOrdentrabajo() {
        return this.ordentrabajo;
    }
    
    public void setOrdentrabajo(Integer ordentrabajo) {
        this.ordentrabajo = ordentrabajo;
    }
    public String getEstadotransaccion() {
        return this.estadotransaccion;
    }
    
    public void setEstadotransaccion(String estadotransaccion) {
        this.estadotransaccion = estadotransaccion;
    }
    public Double getDescuento1() {
        return this.descuento1;
    }
    
    public void setDescuento1(Double descuento1) {
        this.descuento1 = descuento1;
    }
    public Double getDescuento2() {
        return this.descuento2;
    }
    
    public void setDescuento2(Double descuento2) {
        this.descuento2 = descuento2;
    }
    public Double getDescuento3() {
        return this.descuento3;
    }
    
    public void setDescuento3(Double descuento3) {
        this.descuento3 = descuento3;
    }
    public Double getDescuento4() {
        return this.descuento4;
    }
    
    public void setDescuento4(Double descuento4) {
        this.descuento4 = descuento4;
    }
    public Integer getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Integer almacen) {
        this.almacen = almacen;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public Integer getNroingreso() {
        return this.nroingreso;
    }
    
    public void setNroingreso(Integer nroingreso) {
        this.nroingreso = nroingreso;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getDisponibilidad() {
        return disponibilidad;
    }

    public void setDisponibilidad(String disponibilidad) {
        this.disponibilidad = disponibilidad;
    }

    public void setPcostoultimo(double parseDouble) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}