package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Detallenota generated by hbm2java
 */
public class Detallenota  implements java.io.Serializable {


     private Integer iddetnota;
     private Cabeces cabeces;
     private Repuestos repuestos;
     private String descripcion;
     private Double valor;
     private Integer cantidad;
     
     

    public Detallenota() {
    }

    public Detallenota(Cabeces cabeces, Repuestos repuestos, String descripcion, Double valor, Integer cantidad) {
       this.cabeces = cabeces;
       this.repuestos = repuestos;
       this.descripcion = descripcion;
       this.valor = valor;
       this.cantidad = cantidad;
    }
   
    public Integer getIddetnota() {
        return this.iddetnota;
    }
    
    public void setIddetnota(Integer iddetnota) {
        this.iddetnota = iddetnota;
    }
    public Cabeces getCabeces() {
        return this.cabeces;
    }
    
    public void setCabeces(Cabeces cabeces) {
        this.cabeces = cabeces;
    }
    public Repuestos getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Repuestos repuestos) {
        this.repuestos = repuestos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


