package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA
/**
 * Detalleproformas generated by hbm2java
 */
public class Detalleproformas  implements java.io.Serializable {


     private Integer iddetproforma;
     private Repuestos repuestos;
     private Cabecproformas cabecproformas;
     private String codrepuesto;
     private Integer cantidad;
     private Double preciolista;
     private Double descuento1;
     private Double descuento2;
     private Double descuento3;
     private Double descuento4;
     private String disponibilidad;
     private String codigoseg;     

    public Detalleproformas() {
    }

    public Detalleproformas(Repuestos repuestos, Cabecproformas cabecproformas, String codrepuesto, Integer cantidad, Double preciolista, Double descuento1, Double descuento2, Double descuento3, Double descuento4
                            ,String disponibilidad, String codigoseg) {
       this.repuestos = repuestos;
       this.cabecproformas = cabecproformas;
       this.codrepuesto = codrepuesto;
       this.cantidad = cantidad;
       this.preciolista = preciolista;
       this.descuento1 = descuento1;
       this.descuento2 = descuento2;
       this.descuento3 = descuento3;
       this.descuento4 = descuento4;
       this.disponibilidad = disponibilidad;
       this.codigoseg = codigoseg;       
    }
   
    public Integer getIddetproforma() {
        return this.iddetproforma;
    }
    
    public void setIddetproforma(Integer iddetproforma) {
        this.iddetproforma = iddetproforma;
    }
    public Repuestos getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Repuestos repuestos) {
        this.repuestos = repuestos;
    }
    public Cabecproformas getCabecproformas() {
        return this.cabecproformas;
    }
    
    public void setCabecproformas(Cabecproformas cabecproformas) {
        this.cabecproformas = cabecproformas;
    }
    public String getCodrepuesto() {
        return this.codrepuesto;
    }
    
    public void setCodrepuesto(String codrepuesto) {
        this.codrepuesto = codrepuesto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPreciolista() {
        return this.preciolista;
    }
    
    public void setPreciolista(Double preciolista) {
        this.preciolista = preciolista;
    }
    public Double getDescuento1() {
        return this.descuento1;
    }
    
    public void setDescuento1(Double descuento1) {
        this.descuento1 = descuento1;
    }
    public Double getDescuento2() {
        return this.descuento2;
    }
    
    public void setDescuento2(Double descuento2) {
        this.descuento2 = descuento2;
    }
    public Double getDescuento3() {
        return this.descuento3;
    }
    
    public void setDescuento3(Double descuento3) {
        this.descuento3 = descuento3;
    }
    public Double getDescuento4() {
        return this.descuento4;
    }
    
    public void setDescuento4(Double descuento4) {
        this.descuento4 = descuento4;
    }

    public String getDisponibilidad() {
        return disponibilidad;
    }

    public void setDisponibilidad(String disponibilidad) {
        this.disponibilidad = disponibilidad;
    }
    
    public String getCodigoseg() {
        return this.codigoseg;
    }

    public void setCodigoseg(String codigoseg) {
        this.codigoseg = codigoseg;
    }    
    
}