package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Detallesugerido generated by hbm2java
 */
public class Detallesugerido  implements java.io.Serializable {


     private Integer iddetallesugerido;
     private Repuestos repuestos;
     private Cabecsugerido cabecsugerido;
     private Integer cantpedida;
     private Integer cantentregada;
     private Double valorfob;
     private Double valorcosto;
     private String partidaaranc;
     private Integer stocksugerido;
     private Integer cantpendiente;
     private Integer demandaprom;
     private Integer totdemanda;

    public Detallesugerido() {
    }

    public Detallesugerido(Repuestos repuestos, Cabecsugerido cabecsugerido, Integer cantpedida, Integer cantentregada, Double valorfob, Double valorcosto, String partidaaranc, Integer stocksugerido, Integer cantpendiente, Integer demandaprom, Integer totdemanda) {
       this.repuestos = repuestos;
       this.cabecsugerido = cabecsugerido;
       this.cantpedida = cantpedida;
       this.cantentregada = cantentregada;
       this.valorfob = valorfob;
       this.valorcosto = valorcosto;
       this.partidaaranc = partidaaranc;
       this.stocksugerido = stocksugerido;
       this.cantpendiente = cantpendiente;
       this.demandaprom = demandaprom;
       this.totdemanda = totdemanda;
    }
   
    public Integer getIddetallesugerido() {
        return this.iddetallesugerido;
    }
    
    public void setIddetallesugerido(Integer iddetallesugerido) {
        this.iddetallesugerido = iddetallesugerido;
    }
    public Repuestos getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Repuestos repuestos) {
        this.repuestos = repuestos;
    }
    public Cabecsugerido getCabecsugerido() {
        return this.cabecsugerido;
    }
    
    public void setCabecsugerido(Cabecsugerido cabecsugerido) {
        this.cabecsugerido = cabecsugerido;
    }
    public Integer getCantpedida() {
        return this.cantpedida;
    }
    
    public void setCantpedida(Integer cantpedida) {
        this.cantpedida = cantpedida;
    }
    public Integer getCantentregada() {
        return this.cantentregada;
    }
    
    public void setCantentregada(Integer cantentregada) {
        this.cantentregada = cantentregada;
    }
    public Double getValorfob() {
        return this.valorfob;
    }
    
    public void setValorfob(Double valorfob) {
        this.valorfob = valorfob;
    }
    public Double getValorcosto() {
        return this.valorcosto;
    }
    
    public void setValorcosto(Double valorcosto) {
        this.valorcosto = valorcosto;
    }
    public String getPartidaaranc() {
        return this.partidaaranc;
    }
    
    public void setPartidaaranc(String partidaaranc) {
        this.partidaaranc = partidaaranc;
    }
    public Integer getStocksugerido() {
        return this.stocksugerido;
    }
    
    public void setStocksugerido(Integer stocksugerido) {
        this.stocksugerido = stocksugerido;
    }
    public Integer getCantpendiente() {
        return this.cantpendiente;
    }
    
    public void setCantpendiente(Integer cantpendiente) {
        this.cantpendiente = cantpendiente;
    }
    public Integer getDemandaprom() {
        return this.demandaprom;
    }
    
    public void setDemandaprom(Integer demandaprom) {
        this.demandaprom = demandaprom;
    }

    public Integer getTotdemanda() {
        return this.totdemanda;
    }
    
    public void setTotdemanda(Integer totdemanda) {
        this.totdemanda = totdemanda;
    }

    public void setTotDemanda(Integer totDemanda) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



}


