package Entidades;
// Generated 27/02/2015 12:38:58 PM by Hibernate Tools 3.6.0



/**
 * Equipos generated by hbm2java
 */
public class Equipos implements java.io.Serializable {


     private int idequipo;
     private String descripcion;
     private Double descuento1;
     private double descuento2;
     private double descuento3;
     private double descuento4;
     private Double totalventa;
     private Double totalcosto;
     private Double margen;
     private String estado;



    public Equipos() {
    }


    public Equipos(int idequipo, String descripcion, String estado) {
        this.idequipo = idequipo;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    
    public Equipos(int idlinea, double descuento2, double descuento3, double descuento4) {
        this.idequipo = idlinea;
        this.descuento2 = descuento2;
        this.descuento3 = descuento3;
        this.descuento4 = descuento4;
    }
    public Equipos(int idlinea, String descripcion, Double descuento1, double descuento2, double descuento3, double descuento4, Double totalventa, Double totalcosto, Double margen) {
       this.idequipo = idlinea;
       this.descripcion = descripcion;
       this.descuento1 = descuento1;
       this.descuento2 = descuento2;
       this.descuento3 = descuento3;
       this.descuento4 = descuento4;
       this.totalventa = totalventa;
       this.totalcosto = totalcosto;
       this.margen = margen;
    }
   
    public int getIdequipo() {
        return this.idequipo;
    }
    
    public void setIdequipo(int idequipo) {
        this.idequipo = idequipo;
    }

  
    
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    public Double getDescuento1() {
        return this.descuento1;
    }
    
    public void setDescuento1(Double descuento1) {
        this.descuento1 = descuento1;
    }
    public double getDescuento2() {
        return this.descuento2;
    }
    
    public void setDescuento2(double descuento2) {
        this.descuento2 = descuento2;
    }
    public double getDescuento3() {
        return this.descuento3;
    }
    
    public void setDescuento3(double descuento3) {
        this.descuento3 = descuento3;
    }
    public double getDescuento4() {
        return this.descuento4;
    }
    
    public void setDescuento4(double descuento4) {
        this.descuento4 = descuento4;
    }
    public Double getTotalventa() {
        return this.totalventa;
    }
    
    public void setTotalventa(Double totalventa) {
        this.totalventa = totalventa;
    }
    public Double getTotalcosto() {
        return this.totalcosto;
    }
    
    public void setTotalcosto(Double totalcosto) {
        this.totalcosto = totalcosto;
    }
    public Double getMargen() {
        return this.margen;
    }
    
    public void setMargen(Double margen) {
        this.margen = margen;
    }




}


