package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estratificacion generated by hbm2java
 */
public class Estratificacion  implements java.io.Serializable {


     private Integer idMov;
     private String codigoestratificacion;
     private String descripcion;
     private Integer ventasdesde;
     private Integer ventashasta;
     private Integer nromeses;
     private Set repuestoses = new HashSet(0);

    public Estratificacion() {
    }

	
    public Estratificacion(String codigoestratificacion) {
        this.codigoestratificacion = codigoestratificacion;
    }
    public Estratificacion(String codigoestratificacion, String descripcion, Integer ventasdesde, Integer ventashasta, Integer nromeses, Set repuestoses) {
       this.codigoestratificacion = codigoestratificacion;
       this.descripcion = descripcion;
       this.ventasdesde = ventasdesde;
       this.ventashasta = ventashasta;
       this.nromeses = nromeses;
       this.repuestoses = repuestoses;
    }
   
    public Integer getIdMov() {
        return this.idMov;
    }
    
    public void setIdMov(Integer idMov) {
        this.idMov = idMov;
    }
    public String getCodigoestratificacion() {
        return this.codigoestratificacion;
    }
    
    public void setCodigoestratificacion(String codigoestratificacion) {
        this.codigoestratificacion = codigoestratificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getVentasdesde() {
        return this.ventasdesde;
    }
    
    public void setVentasdesde(Integer ventasdesde) {
        this.ventasdesde = ventasdesde;
    }
    public Integer getVentashasta() {
        return this.ventashasta;
    }
    
    public void setVentashasta(Integer ventashasta) {
        this.ventashasta = ventashasta;
    }
    public Integer getNromeses() {
        return this.nromeses;
    }
    
    public void setNromeses(Integer nromeses) {
        this.nromeses = nromeses;
    }
    public Set getRepuestoses() {
        return this.repuestoses;
    }
    
    public void setRepuestoses(Set repuestoses) {
        this.repuestoses = repuestoses;
    }




}


