package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Importadores generated by hbm2java
 */
public class Importadores  implements java.io.Serializable {


     private Integer idimportador;
     private String nombre;
     private String direccion;
     private String pais;
     private String telefono;
     private String telefono2;
     private String email;
     private String contacto;
     private Set cabecsugeridos = new HashSet(0);

    public Importadores() {
    }

    public Importadores(String nombre, String direccion, String pais, String telefono, String telefono2, String email, String contacto, Set cabecsugeridos) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.pais = pais;
       this.telefono = telefono;
       this.telefono2 = telefono2;
       this.email = email;
       this.contacto = contacto;
       this.cabecsugeridos = cabecsugeridos;
    }
   
    public Integer getIdimportador() {
        return this.idimportador;
    }
    
    public void setIdimportador(Integer idimportador) {
        this.idimportador = idimportador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set getCabecsugeridos() {
        return this.cabecsugeridos;
    }
    
    public void setCabecsugeridos(Set cabecsugeridos) {
        this.cabecsugeridos = cabecsugeridos;
    }




}


