package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Operaciones generated by hbm2java
 */
public class Operaciones  implements java.io.Serializable {


     private Integer idoperacion;
     private String codigooperacion;
     private String descripcion;
     private String verstock;
     private String costos;
     private String transaccion;
     private Set sistemas = new HashSet(0);
     private Set detalleeses = new HashSet(0);

    public Operaciones() {
    }

	
    public Operaciones(String codigooperacion) {
        this.codigooperacion = codigooperacion;
    }
    public Operaciones(String codigooperacion, String descripcion, String verstock, String costos, String transaccion, Set sistemas, Set detalleeses) {
       this.codigooperacion = codigooperacion;
       this.descripcion = descripcion;
       this.verstock = verstock;
       this.costos = costos;
       this.transaccion = transaccion;
       this.sistemas = sistemas;
       this.detalleeses = detalleeses;
    }
   
    public Integer getIdoperacion() {
        return this.idoperacion;
    }
    
    public void setIdoperacion(Integer idoperacion) {
        this.idoperacion = idoperacion;
    }
    public String getCodigooperacion() {
        return this.codigooperacion;
    }
    
    public void setCodigooperacion(String codigooperacion) {
        this.codigooperacion = codigooperacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getVerstock() {
        return this.verstock;
    }
    
    public void setVerstock(String verstock) {
        this.verstock = verstock;
    }
    public String getCostos() {
        return this.costos;
    }
    
    public void setCostos(String costos) {
        this.costos = costos;
    }
    public String getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(String transaccion) {
        this.transaccion = transaccion;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }
    public Set getDetalleeses() {
        return this.detalleeses;
    }
    
    public void setDetalleeses(Set detalleeses) {
        this.detalleeses = detalleeses;
    }




}


