package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Pagos generated by hbm2java
 */
public class Pagos  implements java.io.Serializable {


     private Integer idpago;
     private Bancos bancos;
     private Cabeces cabeces;
     private Cabecsalvar cabecsalvar;
     private Usuarios usuarios;
     private String tipodoc;
     private String nrodocumento;
     private Date fecha;
     private Double importe;
     private String forma;
     private String nrocheque;
     private Integer almacen;
     private String idsalida;
     private String rutaimagenes;
     
    public Pagos() {
    }

    public Pagos(Bancos bancos, Cabeces cabeces, Usuarios usuarios, String tipodoc, String nrodocumento, Date fecha, Double importe, String forma, String nrocheque, Integer almacen, String idsalida, String rutaImagenes) {
       this.bancos = bancos;
       this.cabeces = cabeces;
       this.usuarios = usuarios;
       this.tipodoc = tipodoc;
       this.nrodocumento = nrodocumento;
       this.fecha = fecha;
       this.importe = importe;
       this.forma = forma;
       this.nrocheque = nrocheque;
       this.almacen = almacen;
       this.idsalida = idsalida;
       this.rutaimagenes = rutaImagenes;

    }
   
    public Integer getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(Integer idpago) {
        this.idpago = idpago;
    }
    public Bancos getBancos() {
        return this.bancos;
    }
    
    public void setBancos(Bancos bancos) {
        this.bancos = bancos;
    }
    public Cabeces getCabeces() {
        return this.cabeces;
    }
    
    public void setCabeces(Cabeces cabeces) {
        this.cabeces = cabeces;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    
    public String getTipodoc() {
        return this.tipodoc;
    }

    public void setTipodoc(String tipodoc) {
        this.tipodoc = tipodoc;
    }

    public String getNrodocumento() {
        return this.nrodocumento;
    }

    public void setNrodocumento(String nrodocumento) {
        this.nrodocumento = nrodocumento;
    }
    
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }
    public String getForma() {
        return this.forma;
    }
    
    public void setForma(String forma) {
        this.forma = forma;
    }
    public String getNrocheque() {
        return this.nrocheque;
    }
    
    public void setNrocheque(String nrocheque) {
        this.nrocheque = nrocheque;
    }
    public Integer getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Integer almacen) {
        this.almacen = almacen;
    }
    public String getIdsalida() {
        return this.idsalida;
    }
    
    public void setIdsalida(String idsalida) {
        this.idsalida = idsalida;
    }

    public Cabecsalvar getCabecsalvar() {
        return cabecsalvar;
    }

    public void setCabecsalvar(Cabecsalvar cabecsalvar) {
        this.cabecsalvar = cabecsalvar;
    }

    public String getRutaimagenes() {
        return rutaimagenes;
    }

    public void setRutaimagenes(String rutaimagenes) {
        this.rutaimagenes = rutaimagenes;
    }
    
}