package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA



/**
 * PaquetesRepuestos generated by hbm2java
 */
public class PaquetesRepuestos  implements java.io.Serializable {


     private Integer idpaqrepuestos;
     private Paquetes paquetes;
     private Repuestos repuestos;
     private Integer cantidad;

    public PaquetesRepuestos() {
    }

    public PaquetesRepuestos(Paquetes paquetes, Repuestos repuestos, Integer cantidad) {
       this.paquetes = paquetes;
       this.repuestos = repuestos;
       this.cantidad = cantidad;
    }
   
    public Integer getIdpaqrepuestos() {
        return this.idpaqrepuestos;
    }
    
    public void setIdpaqrepuestos(Integer idpaqrepuestos) {
        this.idpaqrepuestos = idpaqrepuestos;
    }
    public Paquetes getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Paquetes paquetes) {
        this.paquetes = paquetes;
    }
    public Repuestos getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Repuestos repuestos) {
        this.repuestos = repuestos;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


