package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Pedidoweb generated by hbm2java
 */
public class Pedidoweb  implements java.io.Serializable {


     private Integer idpedido;
     private Cabecweb cabecweb;
     private Repuestos repuestos;
     private Integer cantpedida;
     private Integer cantentregada;
     private Double preciolista;
     
     private double descuento1;
     private double descuento2;
     private double descuento3;
     private double descuento4;

    public Pedidoweb() {
    }

    public Pedidoweb(Cabecweb cabecweb, Repuestos repuestos, Integer cantpedida, Integer cantentregada, Double preciolista,
            double descuento1, double descuento2, double descuento3, double descuento4) {
       this.cabecweb = cabecweb;
       this.repuestos = repuestos;
       this.cantpedida = cantpedida;
       this.cantentregada = cantentregada;
       this.preciolista = preciolista;
       
       this.descuento1 = descuento1;
       this.descuento2 = descuento2;
       this.descuento3 = descuento3;
       this.descuento4 = descuento4;
    }
   
    public Integer getIdpedido() {
        return this.idpedido;
    }
    
    public void setIdpedido(Integer idpedido) {
        this.idpedido = idpedido;
    }
    public Cabecweb getCabecweb() {
        return this.cabecweb;
    }
    
    public void setCabecweb(Cabecweb cabecweb) {
        this.cabecweb = cabecweb;
    }
    public Repuestos getRepuestos() {
        return this.repuestos;
    }
    
    public void setRepuestos(Repuestos repuestos) {
        this.repuestos = repuestos;
    }
    public Integer getCantpedida() {
        return this.cantpedida;
    }
    
    public void setCantpedida(Integer cantpedida) {
        this.cantpedida = cantpedida;
    }
    public Integer getCantentregada() {
        return this.cantentregada;
    }
    
    public void setCantentregada(Integer cantentregada) {
        this.cantentregada = cantentregada;
    }
    public Double getPreciolista() {
        return this.preciolista;
    }
    
    public void setPreciolista(Double preciolista) {
        this.preciolista = preciolista;
    }

    public double getDescuento1() {
        return this.descuento1;
    }
    
    public void setDescuento1(double descuento1) {
        this.descuento1 = descuento1;
    }
    public double getDescuento2() {
        return this.descuento2;
    }
    
    public void setDescuento2(double descuento2) {
        this.descuento2 = descuento2;
    }
    public double getDescuento3() {
        return this.descuento3;
    }
    
    public void setDescuento3(double descuento3) {
        this.descuento3 = descuento3;
    }
    public double getDescuento4() {
        return this.descuento4;
    }
    
    public void setDescuento4(double descuento4) {
        this.descuento4 = descuento4;
    }


}


