package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Programas generated by hbm2java
 */
public class Programas  implements java.io.Serializable {


     private Integer idprograma;
     private String descripcion;
     private String codprograma;
     private Set roleses = new HashSet(0);

    public Programas() {
    }

	
    public Programas(String codprograma) {
        this.codprograma = codprograma;
    }
    public Programas(String descripcion, String codprograma, Set roleses) {
       this.descripcion = descripcion;
       this.codprograma = codprograma;
       this.roleses = roleses;
    }
   
    public Integer getIdprograma() {
        return this.idprograma;
    }
    
    public void setIdprograma(Integer idprograma) {
        this.idprograma = idprograma;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodprograma() {
        return this.codprograma;
    }
    
    public void setCodprograma(String codprograma) {
        this.codprograma = codprograma;
    }
    public Set getRoleses() {
        return this.roleses;
    }
    
    public void setRoleses(Set roleses) {
        this.roleses = roleses;
    }




}


