package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RenovacionLetra generated by hbm2java
 */
public class RenovacionLetra  implements java.io.Serializable {


     private Integer idrenovacionletra;
     private Cabeces cabeces;
     private String nroenova;
     private Date fechaEmision;
     private Double totalLetra;
     private Date fechaVence;

    public RenovacionLetra() {
    }

	
    public RenovacionLetra(String nroenova) {
        this.nroenova = nroenova;
    }
    public RenovacionLetra(Cabeces cabeces, String nroenova, Date fechaEmision, Double totalLetra, Date fechaVence) {
       this.cabeces = cabeces;
       this.nroenova = nroenova;
       this.fechaEmision = fechaEmision;
       this.totalLetra = totalLetra;
       this.fechaVence = fechaVence;
    }
   
    public Integer getIdrenovacionletra() {
        return this.idrenovacionletra;
    }
    
    public void setIdrenovacionletra(Integer idrenovacionletra) {
        this.idrenovacionletra = idrenovacionletra;
    }
    public Cabeces getCabeces() {
        return this.cabeces;
    }
    
    public void setCabeces(Cabeces cabeces) {
        this.cabeces = cabeces;
    }
    public String getNroenova() {
        return this.nroenova;
    }
    
    public void setNroenova(String nroenova) {
        this.nroenova = nroenova;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }
    public Double getTotalLetra() {
        return this.totalLetra;
    }
    
    public void setTotalLetra(Double totalLetra) {
        this.totalLetra = totalLetra;
    }
    public Date getFechaVence() {
        return this.fechaVence;
    }
    
    public void setFechaVence(Date fechaVence) {
        this.fechaVence = fechaVence;
    }




}


