package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA



/**
 * RepuestosId generated by hbm2java
 */
public class RepuestosId  implements java.io.Serializable {

    private int idrepuesto;
    private int idlinea;

    public RepuestosId() {
    }
    
    public RepuestosId(int idrepuesto) {
       this.idrepuesto = idrepuesto;       
    }
    
    public RepuestosId(int idrepuesto, int idlinea) {
       this.idrepuesto = idrepuesto;
       this.idlinea = idlinea;
    }
   
    public int getIdrepuesto() {
        return this.idrepuesto;
    }
    
    public void setIdrepuesto(int idrepuesto) {
        this.idrepuesto = idrepuesto;
    }
    
    public int getIdlinea() {
        return this.idlinea;
    }
    
    public void setIdlinea(int idlinea) {
        this.idlinea = idlinea;
    }

    public boolean equals(Object other) {
         if ( (this == other ) ) return true;
         if ( (other == null ) ) return false;
         if ( !(other instanceof RepuestosId) ) return false;
         RepuestosId castOther = ( RepuestosId ) other; 
         
         return (this.getIdrepuesto()==castOther.getIdrepuesto())
                 && (this.getIdlinea()==castOther.getIdlinea());
    }
   
    public int hashCode() {
         int result = 17;     
         result = 37 * result + this.getIdrepuesto();
         result = 37 * result + this.getIdlinea();
         return result;
    }
}