package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idrol;
     private String codigorol;
     private String nombre;
     private Set usuarioses = new HashSet(0);
     private Set programases = new HashSet(0);
     private Set controls = new HashSet(0);

    public Roles() {
    }

    public Roles(String codigorol, String nombre, Set usuarioses, Set programases, Set controls) {
       this.codigorol = codigorol;
       this.nombre = nombre;
       this.usuarioses = usuarioses;
       this.programases = programases;
       this.controls = controls;
    }
   
    public Integer getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(Integer idrol) {
        this.idrol = idrol;
    }
    public String getCodigorol() {
        return this.codigorol;
    }
    
    public void setCodigorol(String codigorol) {
        this.codigorol = codigorol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getProgramases() {
        return this.programases;
    }
    
    public void setProgramases(Set programases) {
        this.programases = programases;
    }
    public Set getControls() {
        return this.controls;
    }
    
    public void setControls(Set controls) {
        this.controls = controls;
    }
    public String toString(){
        return nombre;
    }

    public static class rol {

        public rol() {
        }
    }



}


