package Entidades;
// Generated 20-jul-2023 3:56:00 by Hibernate Tools 3.6.0



/**
 * SalesReport generated by hbm2java
 */
public class SalesReport  implements java.io.Serializable {


     private int idReporte;
     private Double totSolAnt;
     private Double totDolAnt;
     private Double totSolSel;
     private Double totDolSel;
     private int mon;
     private Integer yea;

    public SalesReport() {
    }

	
    public SalesReport(int idReporte, int mon) {
        this.idReporte = idReporte;
        this.mon = mon;
    }
    public SalesReport(int idReporte, Double totSolAnt, Double totDolAnt, Double totSolSel, Double totDolSel, int mon, Integer yea) {
       this.idReporte = idReporte;
       this.totSolAnt = totSolAnt;
       this.totDolAnt = totDolAnt;
       this.totSolSel = totSolSel;
       this.totDolSel = totDolSel;
       this.mon = mon;
       this.yea = yea;
    }
   
    public int getIdReporte() {
        return this.idReporte;
    }
    
    public void setIdReporte(int idReporte) {
        this.idReporte = idReporte;
    }
    public Double getTotSolAnt() {
        return this.totSolAnt;
    }
    
    public void setTotSolAnt(Double totSolAnt) {
        this.totSolAnt = totSolAnt;
    }
    public Double getTotDolAnt() {
        return this.totDolAnt;
    }
    
    public void setTotDolAnt(Double totDolAnt) {
        this.totDolAnt = totDolAnt;
    }
    public Double getTotSolSel() {
        return this.totSolSel;
    }
    
    public void setTotSolSel(Double totSolSel) {
        this.totSolSel = totSolSel;
    }
    public Double getTotDolSel() {
        return this.totDolSel;
    }
    
    public void setTotDolSel(Double totDolSel) {
        this.totDolSel = totDolSel;
    }
    public int getMon() {
        return this.mon;
    }
    
    public void setMon(int mon) {
        this.mon = mon;
    }
    public Integer getYea() {
        return this.yea;
    }
    
    public void setYea(Integer yea) {
        this.yea = yea;
    }




}


