package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA

/**
 * Sistema generated by hbm2java
 */
public class Sistema  implements java.io.Serializable {
     private Integer idtransaccion;
     private Operaciones operaciones;
     private String tipodoc;
     private int serie;
     private Integer ultimonumero;
     private String descripcion;
     private String transaccion;
     
     private String codDocElect;

    public Sistema() {
    }
	
    public Sistema(String tipodoc, int serie) {
        this.tipodoc = tipodoc;
        this.serie = serie;
    }
    
    public Sistema(Operaciones operaciones, String tipodoc, int serie, Integer ultimonumero, String descripcion, String transaccion,
                   String codDocElect) {
       this.operaciones = operaciones;
       this.tipodoc = tipodoc;
       this.serie = serie;
       this.ultimonumero = ultimonumero;
       this.descripcion = descripcion;
       this.transaccion = transaccion;
       
       this.codDocElect = codDocElect;
    }
   
    public Integer getIdtransaccion() {
        return this.idtransaccion;
    }
    
    public void setIdtransaccion(Integer idtransaccion) {
        this.idtransaccion = idtransaccion;
    }
    
    public Operaciones getOperaciones() {
        return this.operaciones;
    }
    
    public void setOperaciones(Operaciones operaciones) {
        this.operaciones = operaciones;
    }
    
    public String getTipodoc() {
        return this.tipodoc;
    }
    
    public void setTipodoc(String tipodoc) {
        this.tipodoc = tipodoc;
    }
    
    public int getSerie() {
        return this.serie;
    }
    
    public void setSerie(int serie) {
        this.serie = serie;
    }
    
    public Integer getUltimonumero() {
        return this.ultimonumero;
    }
    
    public void setUltimonumero(Integer ultimonumero) {
        this.ultimonumero = ultimonumero;
    }
    
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    public String getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(String transaccion) {
        this.transaccion = transaccion;
    }

    public String getCodDocElect() {
        return codDocElect;
    }

    public void setCodDocElect(String codDocElect) {
        this.codDocElect = codDocElect;
    }
}