package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Tramites generated by hbm2java
 */
public class Tramites  implements java.io.Serializable {


     private int idtramite;
     private Cabecsugerido cabecsugerido;
     private String glosa;
     private Double importe;

    public Tramites() {
    }

	
    public Tramites(int idtramite) {
        this.idtramite = idtramite;
    }
    public Tramites(int idtramite, Cabecsugerido cabecsugerido, String glosa, Double importe) {
       this.idtramite = idtramite;
       this.cabecsugerido = cabecsugerido;
       this.glosa = glosa;
       this.importe = importe;
    }
   
    public int getIdtramite() {
        return this.idtramite;
    }
    
    public void setIdtramite(int idtramite) {
        this.idtramite = idtramite;
    }
    public Cabecsugerido getCabecsugerido() {
        return this.cabecsugerido;
    }
    
    public void setCabecsugerido(Cabecsugerido cabecsugerido) {
        this.cabecsugerido = cabecsugerido;
    }
    public String getGlosa() {
        return this.glosa;
    }
    
    public void setGlosa(String glosa) {
        this.glosa = glosa;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }




}


