package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Transportistas generated by hbm2java
 */
public class Transportistas  implements java.io.Serializable {


     private Integer idtransportista;
     private String ruc;
     private String nombre;
     private String direccion;
     private String telefono;
     private String telefono2;
     private Set clienteses = new HashSet(0);
     private Set cabeceses = new HashSet(0);

    public Transportistas() {
    }

    public Transportistas(String ruc, String nombre, String direccion, String telefono, String telefono2, Set clienteses, Set cabeceses) {
       this.ruc = ruc;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.telefono2 = telefono2;
       this.clienteses = clienteses;
       this.cabeceses = cabeceses;
    }
   
    public Integer getIdtransportista() {
        return this.idtransportista;
    }
    
    public void setIdtransportista(Integer idtransportista) {
        this.idtransportista = idtransportista;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }
    public Set getCabeceses() {
        return this.cabeceses;
    }
    
    public void setCabeceses(Set cabeceses) {
        this.cabeceses = cabeceses;
    }
    public String toString(){
        return nombre;
    }



}


