package Entidades;
// Generated 17/09/2013 02:56:16 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idusuario;
     private Roles roles;
     private String nombre;
     private String clave;
     private Date fechaExp;
     private Integer estado;
     private String impresora;
     private Set cabecwebs = new HashSet(0);
     private Set cabeceses = new HashSet(0);
     private Set pagoses = new HashSet(0);
     private Set cabecsalvars = new HashSet(0);
    public String getRoles;

    public Usuarios() {
    }

    public Usuarios(Roles roles, String nombre, String clave, Date fechaExp, Integer estado, String impresora, Set cabecwebs, Set cabeceses, Set pagoses, Set cabecsalvars) {
       this.roles = roles;
       this.nombre = nombre;
       this.clave = clave;
       this.fechaExp = fechaExp;
       this.estado = estado;
       this.impresora = impresora;
       this.cabecwebs = cabecwebs;
       this.cabeceses = cabeceses;
       this.pagoses = pagoses;
       this.cabecsalvars = cabecsalvars;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Roles getRoles() {
        return this.roles;
    }
   
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Date getFechaExp() {
        return this.fechaExp;
    }
    
    public void setFechaExp(Date fechaExp) {
        this.fechaExp = fechaExp;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getCabecwebs() {
        return this.cabecwebs;
    }
    
    public void setCabecwebs(Set cabecwebs) {
        this.cabecwebs = cabecwebs;
    }
    public Set getCabeceses() {
        return this.cabeceses;
    }
    
    public void setCabeceses(Set cabeceses) {
        this.cabeceses = cabeceses;
    }
    public Set getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }
    public Set getCabecsalvars() {
        return this.cabecsalvars;
    }
    
    public void setCabecsalvars(Set cabecsalvars) {
        this.cabecsalvars = cabecsalvars;
    }

    public String getImpresora() {
        return this.impresora;
    }
    
    public void setImpresora(String impresora) {
        this.impresora = impresora;
    }
}