package Presentacion.Facturacion;

import Entidades.Cabecproformas;
import Servicios.TipoMensaje;
import Servicios.facturacion.Servicio_Documentos;
import java.text.SimpleDateFormat;
import javax.swing.table.TableModel;

public class IU_DatosFacturaProforma extends javax.swing.JFrame {

    Cabecproformas cabecProforma;
    TableModel tablaProforma;
    int filaSeleccionada;
    TipoMensaje tipoMensaje;
    
    Servicio_Documentos servicioDocumento;
            
    public IU_DatosFacturaProforma(Cabecproformas cabecProforma, TableModel tablaProforma, int filaSeleccionada) {
        initComponents();
        this.cabecProforma = cabecProforma;
        this.tablaProforma = tablaProforma;
        this.filaSeleccionada = filaSeleccionada;
        tipoMensaje = new TipoMensaje();
        inicializarCampos();
    }

    private void inicializarCampos() {
        
        txtNumProforma.setText(cabecProforma.getCodigocabproforma());
        txtNumFactura.setText(cabecProforma.getNrofactura());
        jdcFechaFactura.setDate(cabecProforma.getFechafact());
        
        txtTransportista.setText(cabecProforma.getTransportista());
        txtNroGuia.setText(cabecProforma.getNroguia());
        jdcFechaDespacho.setDate(cabecProforma.getFechadespacho());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel5 = new javax.swing.JLabel();
        txtNumFactura2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdcFechaFactura = new com.toedter.calendar.JDateChooser();
        txtNumFactura = new javax.swing.JTextField();
        txtNumProforma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTransportista = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNroGuia = new javax.swing.JTextField();
        jdcFechaDespacho = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setText("Nº FACTURA");

        txtNumFactura2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumFactura2KeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MODIFICAR FACTURA PROVEEDOR");
        setResizable(false);

        jLabel2.setText("FECHA FACTURA");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nº FACTURA");

        jdcFechaFactura.setDateFormatString("dd-MM-yyyy");

        txtNumFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumFacturaKeyTyped(evt);
            }
        });

        txtNumProforma.setEditable(false);

        jLabel3.setText("Nº PROFORMA");

        jLabel4.setText("TRANSPORTISTA");

        txtTransportista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTransportistaKeyTyped(evt);
            }
        });

        jLabel6.setText("Nº GUÍA");

        txtNroGuia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroGuiaKeyTyped(evt);
            }
        });

        jdcFechaDespacho.setDateFormatString("dd-MM-yyyy");

        jLabel7.setText("FECHA DESPACHO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jdcFechaFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumProforma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNroGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTransportista))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jdcFechaDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumProforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNroGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jdcFechaFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jdcFechaDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(873, 240));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        int confirmacion = tipoMensaje.Confirmacion("¿ Está seguro de actualizar los datos ?");
        
        if ( confirmacion == tipoMensaje.SI ) {
            String numeroFactura = txtNumFactura.getText();
            cabecProforma.setNrofactura(numeroFactura);
            cabecProforma.setFechafact(jdcFechaFactura.getDate());
            cabecProforma.setTransportista(txtTransportista.getText());
            cabecProforma.setNroguia(txtNroGuia.getText());
            cabecProforma.setFechadespacho(jdcFechaDespacho.getDate());
            
            servicioDocumento = new Servicio_Documentos();
            
            if ( servicioDocumento.actualizarCabecProforma(cabecProforma) ) {
                tipoMensaje.Mensaje(tipoMensaje.EXITO_MODIFICAR);
                tablaProforma.setValueAt(numeroFactura , filaSeleccionada, 3);
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                String fechaFormateada = formatoFecha.format(jdcFechaFactura.getDate());
                tablaProforma.setValueAt(fechaFormateada, filaSeleccionada, 4);
                
            } else {
                tipoMensaje.Mensaje(tipoMensaje.ERROR_MODIFICAR);
            }
        }
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNumFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumFacturaKeyTyped
        
        if ( txtNumFactura.getText().length() == 12 ) {
            evt.consume();
        }
        
        char caracter = evt.getKeyChar();
        
        if ( !(caracter >= '0' && caracter <= '9') && caracter != '-') {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumFacturaKeyTyped

    private void txtTransportistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTransportistaKeyTyped
        
        if ( txtTransportista.getText().length() == 50 ) {
            evt.consume();
        }
        
        char caracter = evt.getKeyChar();
        if ( caracter >= 'a' && caracter <= 'z' ) {
            evt.setKeyChar( (char) (caracter - 32) );
            
        } else if ( caracter == 'ñ') {
            char nuevo = 'Ñ';
            evt.setKeyChar(nuevo);
            
        } else if ( caracter >= 'A' && caracter <= 'Z' || caracter == ' ' || caracter == 'Ñ' ) {
            evt.setKeyChar(caracter);
            
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtTransportistaKeyTyped

    private void txtNumFactura2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumFactura2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFactura2KeyTyped

    private void txtNroGuiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroGuiaKeyTyped
        
        if ( txtNroGuia.getText().length() == 30 ) {
            evt.consume();
        }
        
        char caracter = evt.getKeyChar();
        if ( caracter >= 'a' && caracter <= 'z' ) {
            evt.setKeyChar( (char) (caracter - 32) );
            
        } else if ( caracter == 'ñ') {
            char nuevo = 'Ñ';
            evt.setKeyChar(nuevo);
            
        } else if ( caracter >= 'A' && caracter <= 'Z' || caracter == ' ' || caracter == 'Ñ' || caracter == '.' || caracter == '-') {
            evt.setKeyChar(caracter);
            
        } else if ( caracter >= '0' && caracter <= '9' ) {
            evt.setKeyChar(caracter);
            
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtNroGuiaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcFechaDespacho;
    private com.toedter.calendar.JDateChooser jdcFechaFactura;
    private javax.swing.JTextField txtNroGuia;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtNumFactura2;
    private javax.swing.JTextField txtNumProforma;
    private javax.swing.JTextField txtTransportista;
    // End of variables declaration//GEN-END:variables
}
