package Presentacion.Facturacion;

import Entidades.Clientes;
import Mantenimiento.ClienteDAO;
import Servicios.facturacion.Servicio_Documentos;
import java.util.Iterator;

public class IU_FiltrarProformas extends javax.swing.JFrame {

    private IU_FProforma iuProforma;
    Servicio_Documentos sf;
    
    public IU_FiltrarProformas(IU_FProforma iuProforma) {
        initComponents();
        this.iuProforma = iuProforma;
        sf = new Servicio_Documentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltroProforma = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_cliente = new javax.swing.JRadioButton();
        rb_estado = new javax.swing.JRadioButton();
        cb_cliente = new javax.swing.JComboBox();
        cb_estado = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jdc_desde = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jdc_hasta = new com.toedter.calendar.JDateChooser();
        btnFiltrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        chFecha = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FILTRAR PROFORMAS");
        setResizable(false);

        bgFiltroProforma.add(rb_cliente);
        rb_cliente.setText("Cliente");
        rb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_clienteMouseClicked(evt);
            }
        });

        bgFiltroProforma.add(rb_estado);
        rb_estado.setText("Estado");
        rb_estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_estadoMouseClicked(evt);
            }
        });

        cb_cliente.setEnabled(false);

        cb_estado.setEnabled(false);

        jLabel1.setText("Desde");

        jdc_desde.setDateFormatString("dd-MM-yyyy");
        jdc_desde.setEnabled(false);

        jLabel2.setText("Hasta");

        jdc_hasta.setDateFormatString("dd-MM-yyyy");
        jdc_hasta.setEnabled(false);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        chFecha.setText("Fecha");
        chFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chFechaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_estado)
                            .addComponent(chFecha))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jdc_desde, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(jdc_hasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cb_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb_cliente)
                        .addGap(18, 18, 18)
                        .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_cliente)
                    .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_estado)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(chFecha))
                    .addComponent(jdc_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jdc_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnSalir))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed

        if ( rb_cliente.isSelected() && !chFecha.isSelected()) { // FILTRO Sólo CLIENTE
            String clienteSeleccionado = String.valueOf(cb_cliente.getSelectedItem());
            
            if ( "TODOS".equals(clienteSeleccionado) ){
                iuProforma.Listar(sf.filtrarCabecproformas(0));
                
            } else {
                Clientes clienteElegido = new ClienteDAO().obtenerClientePorNombre(clienteSeleccionado);
                iuProforma.Listar(sf.filtrarCabecproformas(clienteElegido.getIdcliente()));
            }
            
        } else if ( rb_estado.isSelected() && !chFecha.isSelected() ) { // FILTRO Sólo ESTADO
            String estadoSeleccionado = String.valueOf(cb_estado.getSelectedItem());
            iuProforma.Listar(sf.filtrarCabecproformas(estadoSeleccionado));
            
        } else if ( !rb_cliente.isSelected() && !rb_estado.isSelected() && chFecha.isSelected()) { // FILTRO Sólo FECHA
            iuProforma.Listar(sf.filtrarCabecproformas(jdc_desde.getDate(), jdc_hasta.getDate()));
            
        } else if ( rb_cliente.isSelected() && chFecha.isSelected() ) { // FILTRO CLIENTE Y FECHA (DOBLE)
            String clienteSeleccionado = String.valueOf(cb_cliente.getSelectedItem());
            Clientes clienteElegido = new ClienteDAO().obtenerClientePorNombre(clienteSeleccionado);
            iuProforma.Listar(sf.filtrarCabecproformas(clienteElegido.getIdcliente(), jdc_desde.getDate(), jdc_hasta.getDate()));
            
        } else if ( rb_estado.isSelected() && chFecha.isSelected() ) { // FILTRO ESTADO Y FECHA (DOBLE)
            String estadoSeleccionado = String.valueOf(cb_estado.getSelectedItem());
            iuProforma.Listar(sf.filtrarCabecproformas(estadoSeleccionado, jdc_desde.getDate(), jdc_hasta.getDate()));
        }
        dispose();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void listarClientes() {
        cb_cliente.removeAllItems();
        Iterator<Clientes> it = sf.getListCli().iterator();
        cb_cliente.addItem("TODOS");
        while (it.hasNext()) {
            cb_cliente.addItem(it.next());
        }
    }
    
    private void rb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_clienteMouseClicked
        if ( rb_cliente.isSelected() ) {
            listarClientes();
            cambiarEstadoFiltros(1);
        }
    }//GEN-LAST:event_rb_clienteMouseClicked

    private void rb_estadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_estadoMouseClicked
        if ( rb_estado.isSelected() ) {
            listarEstadosProforma();
            cambiarEstadoFiltros(2);
        }
    }//GEN-LAST:event_rb_estadoMouseClicked

    private void chFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chFechaMouseClicked
        cambiarEstadoFiltros(3);
    }//GEN-LAST:event_chFechaMouseClicked

    private void listarEstadosProforma() {
        cb_estado.removeAllItems();
        String[] estados = {"TODOS", "PENDIENTE", "RECHAZADO"};
        for ( int i = 0; i < estados.length; i++ ){
            cb_estado.addItem(estados[i]);
        }
    }
    
    private void cambiarEstadoFiltros(int opcion) {
        
        switch (opcion){
            case 1: cb_cliente.setEnabled(true);
                    cb_estado.setEnabled(false);
                    cb_estado.removeAllItems();
                    break;
                
            case 2: cb_cliente.removeAllItems();
                    cb_cliente.setEnabled(false);
                    cb_estado.setEnabled(true);
                    break;
                
            case 3: cb_cliente.setEnabled(true);
                    cb_estado.setEnabled(true);
                    
                    if ( chFecha.isSelected() ) {
                        jdc_desde.setEnabled(true);
                        jdc_hasta.setEnabled(true);
                        
                    } else {
                        jdc_desde.setDate(null);
                        jdc_hasta.setDate(null);
                        jdc_desde.setEnabled(false);
                        jdc_hasta.setEnabled(false);
                    }
                    break;
        }
        repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFiltroProforma;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cb_cliente;
    private javax.swing.JComboBox cb_estado;
    private javax.swing.JCheckBox chFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdc_desde;
    private com.toedter.calendar.JDateChooser jdc_hasta;
    private javax.swing.JRadioButton rb_cliente;
    private javax.swing.JRadioButton rb_estado;
    // End of variables declaration//GEN-END:variables
}
